export const FETCH_DIALOGFLOW_REQUEST = "FETCH_DIALOGFLOW_REQUEST";
export const FETCH_DIALOGFLOW_SUCCESS = "FETCH_DIALOGFLOW_SUCCESS";
export const FETCH_DIALOGFLOW_FAILURE = "FETCH_DIALOGFLOW_FAILURE";